# Generated by Django 5.2.1 on 2025-06-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Lutador',
            fields=[
                ('id_lutador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField(default=18)),
                ('profissao', models.CharField(default='Desconhecida', max_length=255)),
                ('historia', models.TextField(default='Sem história cadastrada.')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='lutadores', to='app_lutadores.usuario')),
            ],
            options={
                'db_table': 'lutador',
            },
        ),
        migrations.CreateModel(
            name='Golpe',
            fields=[
                ('id_golpe', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('forca', models.CharField(max_length=30)),
                ('lutador', models.ForeignKey(db_column='id_lutador', on_delete=django.db.models.deletion.CASCADE, related_name='golpes', to='app_lutadores.lutador')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='golpes', to='app_lutadores.usuario')),
            ],
            options={
                'db_table': 'golpe',
            },
        ),
        migrations.CreateModel(
            name='Inimizade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inimigo', models.ForeignKey(db_column='id_inimigo', on_delete=django.db.models.deletion.CASCADE, related_name='inimigos_de', to='app_lutadores.lutador')),
                ('lutador', models.ForeignKey(db_column='id_lutador', on_delete=django.db.models.deletion.CASCADE, related_name='inimizades', to='app_lutadores.lutador')),
            ],
            options={
                'db_table': 'inimizades',
                'unique_together': {('lutador', 'inimigo')},
            },
        ),
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amigo', models.ForeignKey(db_column='id_amigo', on_delete=django.db.models.deletion.CASCADE, related_name='amigos_de', to='app_lutadores.lutador')),
                ('lutador', models.ForeignKey(db_column='id_lutador', on_delete=django.db.models.deletion.CASCADE, related_name='amizades', to='app_lutadores.lutador')),
            ],
            options={
                'db_table': 'amizades',
                'unique_together': {('lutador', 'amigo')},
            },
        ),
    ]
