# Generated by Django 5.2.1 on 2025-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lutadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutador',
            name='hash_imagem',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
