# Generated by Django 5.2.1 on 2025-05-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lutadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golpe',
            name='usuario',
        ),
    ]
