# Generated by Django 5.2.1 on 2025-05-27 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lutadores', '0002_remove_golpe_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='golpe',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='golpes', to='app_lutadores.usuario'),
            preserve_default=False,
        ),
    ]
